name: Build, Push Docker Image and Deploy with Terraform

on:
  pull_request:
    branches: 
      - main
    types: [closed]

env:
  ECR_URL : 789524919849.dkr.ecr.us-east-1.amazonaws.com
  IMG_NAME : img-catapult-healthcare-chatbot
  IMAGE_TAG : latest
  TF_WORKING_DIR: terraform

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      - name: Build Docker image
        run: make build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Check if ECR repository exists
        id: check-ecr-repo
        run: |
          aws ecr describe-repositories --repository-names ${{ env.IMG_NAME }} || exit 0
          echo "::set-output name=exists::true"

      - name: Create ECR repository if it doesn't exist
        if: steps.check-ecr-repo.outputs.exists != 'true'
        run: |
          aws ecr create-repository --repository-name ${{ env.IMG_NAME }}
          echo "::set-output name=created::true"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag Docker image
        run: |
          make image-tag IMAGE_TAG=${{ env.IMAGE_TAG }}

      - name: Push Docker image to Amazon ECR
        run: docker push ${{ env.ECR_URL }}/${{ env.IMG_NAME }}:${{ env.IMAGE_TAG }}


  deploy-with-terraform:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy using Terraform
        run: |
          cd $TF_WORKING_DIR
          terraform init
          terraform plan -out=tfplan
          terraform apply tfplan

  lambda-function:
    needs: deploy-with-terraform
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create or Update Lambda Function
        run: |
          set -e
          if make update-lambda; then
            echo "Lambda function updated successfully"
          else
            echo "Lambda function not found, creating new function"
            make create-lambda
          fi