# .streamlit/secrets.toml


OPENAI_API_KEY = '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'

[connections.snowflake]
user = 'QUBIKA_ELHAIEK'
password = 'Momaso123!'
warehouse = 'ML_ENGINEER_WH'
role = '_ML_ENGINEER_CATAPULT_HEALTH_DB'
account = 'nqhycck-oh54539'
